### ISSUE TITLE
MarkSweepCompact 80ms every 1 sec spike

### ISSUE THREAD

**Issue by getnamo** [ncsoft/Unreal.js-core#3] opened 2016-07-01 19:11 UTC
Ever seen this behavior? Occurs both in editor and in Play in Editor. On my laptop every 1 second a 80ms spike is caused by MarkSweepCompact even in a map with no js component attached. When the plugin is disabled the problem goes away, re-enabled it comes back. I've attached two profiling runs for your inspection in Session Frontend.

[UnrealStats.zip](https://github.com/ncsoft/Unreal.js-core/files/344032/UnrealStats.zip)

![marksweepcompact](https://cloud.githubusercontent.com/assets/542365/16532062/8452a276-3f9d-11e6-88ac-8a4111b31a13.png)

**Comment by nakosung** [comment] 2016-07-02 09:11
I haven't noticed those periodic hitches occurred by V8 GC yet. It implies OnTick dispatcher creates V8 objects, which should be recycled. (Or there are some serious memory leakage in Unreal.js)

There are several GC related options available for V8. You can pass v8 options in settings-plugins-unreal.js-v8 options. :)

I think most options available in node.js can be used with unreal.js. https://gist.github.com/listochkin/10973974

---

I confirmed that periodic hitches occurred by V8 GC. I'll investigate further about what triggers GC.

**Comment by nakosung** [comment] 2016-07-02 12:17
with `--trace-gc --log-gc`, I got following logs. It indicates there are serious memory leakage for current unreal.js. :open_mouth: 

```
[7824:000001C3A99505C0]    54060 ms: Mark-sweep 104.7 (147.8) -> 102.3 (147.8) MB, 105.5 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    55011 ms: Mark-sweep 109.6 (147.8) -> 102.3 (147.8) MB, 83.7 / 0.1 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    56030 ms: Mark-sweep 109.7 (147.8) -> 102.4 (147.8) MB, 95.7 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    57019 ms: Mark-sweep 109.8 (147.8) -> 102.4 (147.8) MB, 93.6 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    58023 ms: Mark-sweep 109.8 (147.8) -> 102.5 (147.8) MB, 95.0 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    59014 ms: Mark-sweep 109.9 (147.8) -> 102.6 (148.8) MB, 88.2 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    60030 ms: Mark-sweep 110.2 (148.8) -> 102.6 (148.8) MB, 96.9 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    61028 ms: Mark-sweep 110.0 (148.8) -> 102.7 (148.8) MB, 103.5 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    62032 ms: Mark-sweep 110.1 (148.8) -> 102.8 (148.8) MB, 102.5 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    63035 ms: Mark-sweep 110.1 (148.8) -> 102.8 (148.8) MB, 105.8 / 0.1 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    64026 ms: Mark-sweep 110.2 (148.8) -> 102.9 (148.8) MB, 100.7 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    65035 ms: Mark-sweep 110.3 (148.8) -> 102.9 (148.8) MB, 100.0 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    66031 ms: Mark-sweep 110.3 (148.8) -> 103.0 (148.8) MB, 101.1 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    67028 ms: Mark-sweep 110.4 (148.8) -> 103.1 (148.8) MB, 101.7 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    68023 ms: Mark-sweep 110.5 (148.8) -> 103.1 (148.8) MB, 97.8 / 0.1 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    69028 ms: Mark-sweep 110.5 (148.8) -> 103.2 (148.8) MB, 100.0 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    70031 ms: Mark-sweep 110.6 (148.8) -> 103.2 (148.8) MB, 96.3 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    71100 ms: Mark-sweep 110.9 (148.8) -> 103.3 (148.8) MB, 130.1 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    72044 ms: Mark-sweep 110.6 (148.8) -> 103.4 (148.8) MB, 110.1 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    73088 ms: Mark-sweep 110.7 (148.8) -> 103.4 (148.8) MB, 153.3 / 0.1 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    73450 ms: Scavenge 119.1 (148.8) -> 103.7 (148.8) MB, 18.3 / 0.0 ms [allocation failure].
[7824:000001C3A99505C0]    73665 ms: Scavenge 119.2 (148.8) -> 103.8 (148.8) MB, 12.3 / 0.0 ms [allocation failure].
[7824:000001C3A99505C0]    74085 ms: Mark-sweep 107.0 (148.8) -> 103.8 (149.8) MB, 89.3 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    75106 ms: Mark-sweep 111.1 (149.8) -> 103.8 (149.8) MB, 101.9 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    76207 ms: Mark-sweep 111.2 (149.8) -> 103.9 (149.8) MB, 174.6 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    77088 ms: Mark-sweep 111.2 (149.8) -> 104.0 (149.8) MB, 96.0 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    78126 ms: Mark-sweep 111.3 (149.8) -> 104.0 (149.8) MB, 127.9 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    79090 ms: Mark-sweep 111.6 (149.8) -> 104.1 (149.8) MB, 97.0 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    80226 ms: Mark-sweep 111.4 (149.8) -> 104.2 (149.8) MB, 172.5 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    81083 ms: Mark-sweep 111.5 (149.8) -> 104.2 (149.8) MB, 91.2 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    82086 ms: Mark-sweep 111.5 (149.8) -> 104.3 (149.8) MB, 91.9 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    83083 ms: Mark-sweep 111.6 (149.8) -> 104.3 (149.8) MB, 91.7 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    84089 ms: Mark-sweep 111.7 (149.8) -> 104.4 (149.8) MB, 97.0 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    85083 ms: Mark-sweep 111.7 (149.8) -> 104.5 (149.8) MB, 91.6 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    86082 ms: Mark-sweep 111.8 (149.8) -> 104.5 (149.8) MB, 88.5 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    87093 ms: Mark-sweep 111.8 (149.8) -> 104.6 (150.8) MB, 96.5 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    88088 ms: Mark-sweep 111.9 (150.8) -> 104.6 (150.8) MB, 95.8 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    89076 ms: Mark-sweep 112.0 (150.8) -> 104.7 (150.8) MB, 84.5 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    90081 ms: Mark-sweep 112.3 (150.8) -> 104.8 (150.8) MB, 88.6 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    91099 ms: Mark-sweep 112.1 (150.8) -> 104.8 (150.8) MB, 98.1 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    92087 ms: Mark-sweep 112.1 (150.8) -> 104.9 (150.8) MB, 94.9 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    93095 ms: Mark-sweep 112.2 (150.8) -> 105.0 (150.8) MB, 96.5 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    94098 ms: Mark-sweep 112.3 (150.8) -> 105.0 (150.8) MB, 102.6 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    95091 ms: Mark-sweep 112.3 (150.8) -> 105.1 (150.8) MB, 95.2 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    96092 ms: Mark-sweep 112.4 (150.8) -> 105.1 (150.8) MB, 95.9 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    97089 ms: Mark-sweep 112.5 (150.8) -> 105.2 (150.8) MB, 96.2 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    98104 ms: Mark-sweep 112.5 (150.8) -> 105.3 (150.8) MB, 100.6 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]    99081 ms: Mark-sweep 112.6 (150.8) -> 105.3 (150.8) MB, 86.2 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]   100099 ms: Mark-sweep 112.6 (150.8) -> 105.4 (150.8) MB, 105.0 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
[7824:000001C3A99505C0]   101106 ms: Mark-sweep 113.0 (150.8) -> 105.5 (151.8) MB, 107.2 / 0.0 ms [Isolate::RequestGarbageCollection] [GC in old space requested].
```

**Comment by nakosung** [comment] 2016-07-02 12:37
Working on adding `memory.takeSnapshot` to investigate heap diff.

6daa9bdbff316d11c70ae602538e108838897b8f added.

It turned out that there was no memory leakage. Even after memory leakage was eliminated, hitches are still observable. `Isolate::RequestGarbageCollection` seems to trigger periodic GC.

**Comment by nakosung** [comment] 2016-07-02 13:19
Okay. Investigating heap dumps reveals what triggers GC unnecessarily. 
![image](https://cloud.githubusercontent.com/assets/2463571/16540526/3b51a8cc-40a3-11e6-9a8d-0cd2f50b5ae6.png)

https://github.com/ncsoft/Unreal.js-core/blob/master/Content/Scripts/polyfill/windowTimers.js
https://github.com/ncsoft/Unreal.js-core/blob/master/Content/Scripts/polyfill/timers.js

**Comment by nakosung** [comment] 2016-07-03 02:02
timer functions reprogrammed. https://github.com/ncsoft/Unreal.js-core/tree/fast_timer 

I checked session frontend by capturing data and confirmed there were no periodic hitches. BTW, I haven't tested new functions enough, so the commit isn't merged yet.

**Comment by getnamo** [comment] 2016-07-04 07:05
Fascinating debug and quick to boot! Will be a few days before I can confirm independently. Great work!

**Comment by getnamo** [comment] 2016-07-08 23:07
Still hitches for me using the same MarkSweepCompact despite updating the polyfills to fast_timer commit. Tested on both laptop and now a high end desktop. Tried to add `--trace-gc --log-gc` according to your instructions, but it doesn't show up in the log, does it get output in a different location?

Maybe you can walk me through the steps to investigate this (heap dumps/etc) and I can help look for the source of the issue?

**Comment by getnamo** [comment] 2016-07-08 23:21
![hitch2](https://cloud.githubusercontent.com/assets/542365/16704077/04f39ade-456b-11e6-8d7e-8f20b52f1284.gif)

Example hitching, again note that it is present both in editor and when PIE. The graph is visible by typing `stat unitgraph` in the console.

**Comment by nakosung** [comment] 2016-07-09 00:10
UMG example isn't optimized for hitches yet. :)

You can narrow down which triggers GC as follows:
1. Make your situation stable, which means no GC should kick in.
2. In Javascript console, memory.takeSnapshot('1.heapsnapshot') and after several seconds, memory.takeSnapshot('2.snapshot'). These snapshots will be dumped into Binaries/{Platform} folder.
3. Open Chrome and press F12(Alt+Opt+I) to bring up console. Load your two dump files by clicking 'Profiles' - 'Load'.
4. Comparing to the other snapshot, you can get an idea what's going on.

FYI,
Google V8 team has a plan to improve GC performance. Please refer to http://v8project.blogspot.kr/2016/04/jank-busters-part-two-orinoco.html.

**Comment by getnamo** [comment] 2016-07-12 19:58
BTW this hitching occurs for me in every example even when no js component is in use, which suggests it is editor context related.

Still looking for some time to debug this more in-depth. Have you noticed this hitching before, is it recent or has this always been present in unreal.js? If you do `stat unitgraph` on an empty project with unreal.js are there instance where you don't see the periodic 1sec garbage collection?

First point is to find out what's causing this, empty projects shouldn't usually take this long to garbage collect .

Second part is if it is unavoidable, are there ways to mitigate it?

Orinoco seems like a great improvement, and some of those improvements made it into v8 5.1 stable (http://v8project.blogspot.co.uk/) since unreal.js is technically on 5.1.300 does that mean we have these improvements already?

Maybe we can use some of the concepts found in this presentation on garbage collection in js (start from page 55), talking about idle time scheduling such that you don't miss a frame: https://ia601503.us.archive.org/32/items/vmss16/titzer.pdf

I also wonder if there is a way to schedule GC to minimally impact game thread, maybe through a background thread unless that is already happening.

**Comment by nakosung** [comment] 2016-07-13 20:25
Unreal.js seems not utilizing idle tasks yet. 
https://github.com/v8/v8/blob/47cce544a31ed5577ffe2963f67acb4144ee0232/src/libplatform/default-platform.cc#L162 

Implementation own platform would make the situation better. :)

**Comment by nakosung** [comment] 2016-07-13 21:09
I've implemented and tested custom platform which supports idle tasks. 

Merged into master branch.

**Comment by getnamo** [comment] 2016-07-14 21:58
So... you know what fixed it?

Removing the *1000 multiplier in elapsed time in timer.js

branch: https://github.com/getnamo/Unreal.js-core/tree/gc-hitch-fix

Some thoughts on this:
-Checked heap dumps and nothing jumped out, but it hit me that the way the timer works now might be creating a lot of temporary variables that now live ~1sec.
-Likely high intervals accumulate a lot of small objects and this causes
the 80ms hitching when gc. More often gc could be cleaning up more efficiently or allowing v8 to do some behind the scenes magic? I don't know the reason for certain though, thoughts?
-Long intervals cause 80ms hitches nearly every frame (e.g. 10000)
-Adjusting the interval to lower values e.g. 250 or 500 causes longer
duration between hitches, but they are still very similar hitches. This is counterintuitive and unless I'm misunderstanding what the bitwise comparator does, breaks the expected correlation.

e.g. 500ms
![500ms timer - hitching](https://cloud.githubusercontent.com/assets/542365/16856832/36254e6a-4a14-11e6-843e-d16fc37cc8c7.png)

-At around 100ms hitching stops and a wavy ripple is visible in
framerate stat unitgraph

![100ms timer](https://cloud.githubusercontent.com/assets/542365/16856845/426be620-4a14-11e6-9cb5-272f362ecc86.png)

-At 1-10 or lower the ripple largely disappears

![1ms timer](https://cloud.githubusercontent.com/assets/542365/16856846/46f8c3c0-4a14-11e6-97f4-7386c5bbc6b4.png)

-The commit is effectively setting the interval to 1

Tested UMG, checked memory leaks, buttery smooth (tiny tiny ripple/variation in the framerate at 120hz, wouldn't ever be noticeable in-game). 

https://github.com/ncsoft/Unreal.js-core/pull/5
Feel free to make the merge after you do your testing.

_This is an aside_
Interesting note about js efficiency atm, this is a for loop using basic es5 (the spikes visible here are when I hit run). So a sample run can count to 100k in about ~5ms?

![100k-all-var](https://cloud.githubusercontent.com/assets/542365/16856913/ae19a79a-4a14-11e6-912c-41e3c73cda1c.png)

when you use es6 const and let appropriately you can now run this 50 times more in a similar time frame. Which means you can have massive gains (50x) if you optimize loops in js.

![5mil-let-const](https://cloud.githubusercontent.com/assets/542365/16856929/c58fde80-4a14-11e6-996c-cbfd58a44f59.png)

**Comment by nakosung** [comment] 2016-07-14 22:53
x 1000 is intended to convert seconds into milliseconds. So after removing multiplier can you still get the right timeout behavior? (`setTimeout(some-kine-of-alert, 1000 /* one second */)`)

**Comment by getnamo** [comment] 2016-07-14 23:14
it does break the behavior let me look a bit deeper into it

**Comment by getnamo** [comment] 2016-07-15 00:23
Ok this has nothing to do with unreal.js-core. It had to do with this example: https://github.com/ncsoft/Unreal.js/blob/master/Examples/Content/Scripts/extension-exampleWindow.js

In that example, you add a refresh function in the tick() of

https://github.com/ncsoft/Unreal.js/blob/master/Examples/Content/Scripts/extension-exampleWindow.js#L346

**Edit:** the function that actually causes the hitching is this one:
https://github.com/ncsoft/Unreal.js/blob/master/Examples/Content/Scripts/extension-exampleWindow.js#L290

As to why that example causes hitching even when the window has been closed, I believe you would better suited to answer that question. 

I've removed the pull request and you can close this issue, added it to https://github.com/ncsoft/Unreal.js/issues/91

Using the temp fix made unreal.js smooth again and it explained why I didn't have the issue before.

**Comment by nakosung** [comment] 2016-07-16 00:46
As you mentioned exampleWindow doesn't catch its close event properly. This is an obvious bug. Thanks! :)

for using 'let' against 'var', I have seen some cases which are not optimized properly by V8 because V8 doesn't fully support 'let' optimization. Do you have some info about using `let` over `var` for performance?

**Comment by getnamo** [comment] 2016-07-16 02:27
There is this: http://stackoverflow.com/questions/21467642/is-there-a-performance-difference-between-let-and-var which shows a mixed message and 10x improvement and this: https://jsfiddle.net/3jp8Lufm/11/ which shows about 2x difference for inside scope. Web results may not apply exactly to how things work in v8 though and we should run something directly comparable to web tests to get an idea of actual performance.

In my example, `const` made a small difference, `let` outside loop probably also small difference, but using `let` for `i` made a huge difference. This is probably due to scoping allowing the compiler to optimize the loop by (I'm speculating) e.g. using a closer placed cache and perhaps create far less temporary variables (in theory it should only create one, but js logic is pretty magic).

The general consensus is you should use `let` and `const` instead of `var` from es6. That said hoisting functions and definitions can be useful in some rare cases.

Also tested the performance of unreal.js setTimeout after reverting it back to normal. It seems you can run ~16,000 timeouts and not notice a performance hit, running 17000+ would create unrecoverable lag (no idea why, these are edge cases anyway).

**Comment by ImmanuelSamuel** [comment] 2016-07-16 10:31
Just letting you know that I am facing this issue as well. (with the fast time commit) ... This is just me opening the editor after copying the plugins folder and building everything. There is no JS component. Is it solved?

**Comment by nakosung** [comment] 2016-07-16 10:45
Removed unnecessary auto refresh to avoid periodic hitches.

**Closed as completed by nakosung** 2016-07-16 10:45 UTC

**Comment by ImmanuelSamuel** [comment] 2016-07-16 10:52
Where is the commit?
